# https://git.reyah.ga/reyah/deployments/npm-cli-login
image: arthurknoep/npm-cli-login:latest

stages:
  - build
  - publish

default:
  before_script:
    - npm-cli-login
    - yarn config set registry "$NPM_REGISTRY"

build:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1h
  cache:
    paths:
      - node_modules/
      - .yarn
  script:
    - yarn install
    - yarn build

publish test version:
  stage: publish
  needs:
    - build
  except:
    refs:
      - master
  script:
    - version=`npm run env | grep npm_package_version= | sed -e "s/npm_package_version=//g"`
    - branch=`echo $CI_COMMIT_BRANCH | tr '/' '-'`
    - yarn publish --new-version="$version-$CI_COMMIT_SHORT_SHA" --tag="$branch" --no-git-tag-version


remove tag:
  stage: publish
  cache:
    paths:
      - node_modules/
      - .yarn
  rules:
    - if: $CI_MERGE_REQUEST_ID && $CI_COMMIT_BRANCH == 'master'
  script:
    - branch=`echo $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME |  tr '/' '-'`
    - package_name=`npm run env | grep npm_package_name= | sed -e "s/npm_package_name=//g"`
    - yarn tag remove $package_name $branch

publish:
  stage: publish
  needs:
    - build
  cache:
    paths:
      - node_modules/
      - .yarn
  only:
    refs:
      - master
  script:
    - env
    - yarn publish --non-interactive


cache:
  paths:
    - node_modules/

