export const ReyahErr = {
    // common
    NoSuchEntity: 'NoSuchEntity',
    NoSuchEntities: 'NoSuchEntities',
    UnknownErr: 'UnknownErr',
    InvalidArg: 'InvalidArg',
    ValidationFatalErr: 'ValidationFatalErr',
    IntrospectionFatalErr: 'IntrospectionFatalErr',
    InvalidFieldValidation: 'InvalidFieldValidation',
    // datamodel
    DataTypeNotFound: 'DataTypeNotFound',
    DataFieldNotFound: 'DataFieldNotFound',
    DataModelHasDependency: 'DataModelHasDependency',
    DocumentHasDependency: 'DocumentHasDependency',
    // datatype
    DataFieldHasDependency: 'DataFieldHasDependency',
    // document
    DataModelNotFound: 'DataModelNotFound',
    FieldNotFound: 'FieldNotFound',
    FieldLinkedTwice: 'FieldLinkedTwice',
    PreviewNotSet: 'PreviewNotSet',
    // invite
    TooManyInvitations: 'TooManyInvitations',
    NoSuchInvitation: 'NoSuchInvitation',
    // job
    JobNotSucceeded: 'JobNotSucceeded',
    DocumentNotUploaded: 'DocumentNotUploaded',
    InvalidContentType: 'InvalidContentType',
    InvalidJobStatus: 'InvalidJobStatus',
    MismatchSizeContentType: 'MismatchSizeContentType',
    InputUnavailable: 'InputUnavailable',
    // oauth
    InvalidScopes: 'InvalidScopes',
    // profile
    InvalidUserId: 'InvalidUserId',
    ProfileAlreadyCreated: 'ProfileAlreadyCreated',
    // routing
    NoSuchPipeline: 'NoSuchPipeline',
    UnhandledPipelineModel: 'UnhandledPipelineModel',
    JobsAlreadyConsumed: 'JobsAlreadyConsumed',
    // user
    UserIdInvalid: 'UserIdInvalid',
    UserNotFound: 'UserNotFound',
};
