name: Build and test
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: arthurknoep/npm-cli-login:latest
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

  deploy:
    name: Publish test version
    needs: build
    runs-on: ubuntu-latest
    container:
      image: arthurknoep/npm-cli-login:latest
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish
        run: |
          version=`npm run env | grep npm_package_version= | sed -e "s/npm_package_version=//g"`
          branch=`echo ${GITHUB_REF#refs/heads/} | tr '/' '-'`
          short_sha=`echo $GITHUB_SHA | cut -c-8`
          npm version --no-git-tag-version --allow-same-version "$version-$short_sha"
          npm publish --tag="$branch"
