name: Build and test
on: push
#  push:
#    branches:
#      - '**'
#      - '!master'


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.reyah.ga'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: persistent-data
          path: |
            dist
            node_modules

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.reyah.ga'
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: persistent-data
      - name: Publish
        run: |
          version=`npm run env | grep npm_package_version= | sed -e "s/npm_package_version=//g"`
          branch=`echo $CI_COMMIT_BRANCH | tr '/' '-'`
          yarn publish --new-version="$version-$CI_COMMIT_SHORT_SHA" --tag="$branch" --no-git-tag-version
